import { useEffect, useState } from 'react'
import { apiFetch } from '../../auth'

type Doctor = { id: string; specialization?: string | null; licenseNumber?: string | null; phone?: string | null; _count: { patients: number }; user: { email: string; firstName: string; lastName: string; isActive: boolean } }
type FormState = { email: string; password: string; firstName: string; lastName: string; specialization: string; licenseNumber: string; phone: string }
const emptyForm: FormState = { email: '', password: '', firstName: '', lastName: '', specialization: '', licenseNumber: '', phone: '' }
async function errorMessage(response: Response) { try { return ((await response.json()) as { message?: string }).message ?? 'Request failed.' } catch { return 'Request failed.' } }

export function AdminDoctorsPage() {
  const [doctors, setDoctors] = useState<Doctor[]>([]); const [form, setForm] = useState(emptyForm); const [editingId, setEditingId] = useState<string | null>(null); const [open, setOpen] = useState(false); const [filters, setFilters] = useState({ name: '', email: '', specialization: '', patients: '' }); const [error, setError] = useState(''); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false)
  async function load() { try { const response = await apiFetch('/admin/doctors'); if (!response.ok) throw new Error('Could not load doctors.'); setDoctors((await response.json()) as Doctor[]); setError('') } catch (loadError) { setError(loadError instanceof Error ? loadError.message : 'Could not load doctors.') } finally { setLoading(false) } }
  useEffect(() => { void load() }, [])
  function openForm(doctor?: Doctor) { setEditingId(doctor?.id ?? null); setForm(doctor ? { email: doctor.user.email, password: '', firstName: doctor.user.firstName, lastName: doctor.user.lastName, specialization: doctor.specialization ?? '', licenseNumber: doctor.licenseNumber ?? '', phone: doctor.phone ?? '' } : emptyForm); setError(''); setOpen(true) }
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); const body = Object.fromEntries(Object.entries(form).filter(([, value]) => value !== '')); const response = await apiFetch(editingId ? `/admin/doctors/${editingId}` : '/admin/doctors', { method: editingId ? 'PATCH' : 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); if (!response.ok) setError(await errorMessage(response)); else { setOpen(false); await load() } setSaving(false) }
  async function remove(doctor: Doctor) { if (!window.confirm(`Remove Dr. ${doctor.user.firstName} ${doctor.user.lastName}?`)) return; const response = await apiFetch(`/admin/doctors/${doctor.id}`, { method: 'DELETE' }); if (!response.ok) setError(await errorMessage(response)); else await load() }
  const visible = doctors.filter((doctor) => `${doctor.user.firstName} ${doctor.user.lastName}`.toLowerCase().includes(filters.name.toLowerCase()) && doctor.user.email.toLowerCase().includes(filters.email.toLowerCase()) && (doctor.specialization ?? '').toLowerCase().includes(filters.specialization.toLowerCase()) && String(doctor._count.patients).includes(filters.patients))
  return <section className="panel admin-management"><div className="section-heading"><div><h2>Doctors</h2><span>{doctors.length} active doctor accounts</span></div><button className="primary-button" onClick={() => openForm()}>Add doctor</button></div><div className="column-filters"><input placeholder="Filter name" value={filters.name} onChange={(event) => setFilters({ ...filters, name: event.target.value })} /><input placeholder="Filter email" value={filters.email} onChange={(event) => setFilters({ ...filters, email: event.target.value })} /><input placeholder="Filter specialization" value={filters.specialization} onChange={(event) => setFilters({ ...filters, specialization: event.target.value })} /><input placeholder="Filter patients" value={filters.patients} onChange={(event) => setFilters({ ...filters, patients: event.target.value })} /><button type="button" onClick={() => setFilters({ name: '', email: '', specialization: '', patients: '' })}>Clear</button></div>{error && <p className="admin-error">{error}</p>}{loading ? <p className="empty-state">Loading doctors...</p> : <div className="data-table admin-table doctor-admin-table"><div className="table-row table-head"><span>Name</span><span>Email</span><span>Specialization</span><span>Patients</span><span>Actions</span></div>{visible.map((doctor) => <div className="table-row" key={doctor.id}><span>Dr. {doctor.user.firstName} {doctor.user.lastName}</span><span>{doctor.user.email}</span><span>{doctor.specialization || '—'}</span><span>{doctor._count.patients}</span><span className="row-actions"><button onClick={() => openForm(doctor)}>Edit</button><button onClick={() => void remove(doctor)}>Delete</button></span></div>)}</div>}{open && <div className="modal-overlay"><div className="modal-card"><div className="modal-header"><h3>{editingId ? 'Edit doctor' : 'Add doctor'}</h3><button onClick={() => setOpen(false)} aria-label="Close">×</button></div><form className="modal-form" onSubmit={submit}><div className="modal-form-grid">{[['firstName','First name'],['lastName','Last name'],['email','Email'],['password',editingId ? 'New password (optional)' : 'Password'],['specialization','Specialization'],['licenseNumber','License number'],['phone','Phone']].map(([key, label]) => <label key={key}>{label}<input type={key === 'password' ? 'password' : key === 'email' ? 'email' : 'text'} required={!editingId && ['firstName','lastName','email','password'].includes(key)} value={form[key as keyof FormState]} onChange={(event) => setForm({ ...form, [key]: event.target.value })} /></label>)}</div>{error && <p className="admin-error">{error}</p>}<button className="primary-button" disabled={saving}>{saving ? 'Saving...' : 'Save doctor'}</button></form></div></div>}</section>
}
